const assert=require('assert');
const fs=require('fs');
const vm=require('vm');
const src=fs.readFileSync('renderer/js/home.js','utf8');
const ctx=vm.createContext({setTimeout:fn=>fn(),escapeHtml:String,lolAPI:{},mmrJadeEstimate:()=>({v:2000,basis:'test'}),addJadeCalibSample(){}});
vm.runInContext(src.slice(src.indexOf('const MMR_BASE'),src.indexOf('// 大乱斗/海斗')),ctx);
vm.runInContext(src.slice(src.indexOf('function mmrAram'),src.indexOf('// ==========',src.indexOf('function mmrAram'))),ctx);
vm.runInContext(src.slice(src.indexOf('function hasRankedQueueData'),src.indexOf('function rankLineOf')),ctx);
(async()=>{
  let calls=[];
  const ranked={queueMap:{RANKED_SOLO_5x5:{tier:'DIAMOND',division:'II',leaguePoints:50},RANKED_FLEX_SR:{tier:'EMERALD',division:'IV',leaguePoints:30}}};
  ctx.lolAPI.lcuRequest=async(method,path)=>{calls.push(path);return calls.length===4?ranked:{__error:'HTTP 500'};};
  assert.equal(await ctx.loadRankedStats('self',true,true),ranked);
  assert.equal(calls.length,4);
  assert(calls[0].endsWith('/current-ranked-stats'));
  calls=[];
  ctx.lolAPI.lcuRequest=async(method,path)=>{calls.push(path);return {__error:'HTTP 500'};};
  assert.equal(await ctx.loadRankedStats('other',false),null);
  assert.equal(calls.length,3);
  assert(calls.every(p=>p.includes('/cached-ranked-stats/other')));
  calls=[];
  await ctx.loadRankedStats('self',true,true,()=>true);
  assert.equal(calls.length,0);
  const chips=ctx.buildHomeMmr(ranked.queueMap,{},50,{puuid:'self'});
  assert(chips.some(c=>c[0]==='单双排'));
  assert(chips.some(c=>c[0]==='灵活组排'));
  assert(ctx.renderHomeMmr(chips,ranked,true,false).includes('历史段位缓存'));
  assert(ctx.renderHomeMmr([],null,false,false).includes('段位暂未获取'));
  assert(ctx.renderHomeMmr([],null,false,true).includes('段位同步中'));
  assert(src.includes('c?.s?.puuid===s.puuid && c?.platformId===targetPlatformId'));
  assert(src.includes("const chipsEl=panel.querySelector('.home-mmr')"));
  assert(src.indexOf('rankedPromise.then(rv=>')>src.indexOf('restoreHomeScroll(s.puuid)'));
  console.log('段位恢复：重试、跨区隔离、取消、缓存提示、单双排/灵活估算与挂载顺序通过');
})().catch(e=>{console.error(e);process.exitCode=1;});
