const assert=require('assert');
const fs=require('fs');
const vm=require('vm');
const src=fs.readFileSync('renderer/js/home.js','utf8');
let now=100000,calls=0;
const context=vm.createContext({Date:{now:()=>now},profileOverride:{puuid:'other'},homeStatsLoading:false,document:{hidden:false},loadHomeStats:async(force,opts)=>{calls++;assert(opts.profileRefresh&&opts.skipCache);}});
vm.runInContext(src.slice(src.indexOf('let profileRefreshAfter'),src.indexOf('async function loadHomeStats')),context);
(async()=>{
  await context.refreshViewedProfile();
  await context.refreshViewedProfile();
  assert.equal(calls,1,'poll must be throttled');
  now+=60001;
  context.homeStatsLoading=true;
  await context.refreshViewedProfile();
  assert.equal(calls,1,'no overlapping requests');
  context.homeStatsLoading=false;
  await context.refreshViewedProfile();
  assert.equal(calls,2);
  now+=60001;context.profileOverride=null;
  await context.refreshViewedProfile();
  assert.equal(calls,2,'do not refresh self through profile flow');
  assert(src.includes('cacheUsable && !skipCache && (!profileOverride || cacheFresh)'));
  assert(src.includes('ts:historyFetchedAt,rankedTs:Date.now()'));
  assert(src.includes('sgpInvalidateMatchHistory?.(profileOverride.puuid)'));
  assert(src.includes('isHomeGameDetailExpanded() || profileBackground'));
  assert(src.includes('if(profileBackground) { homeScrollSnapshot=null; return; }'));
  assert(src.includes('if (!profileBackground && !stale() && panel)'));
  console.log('他人战绩刷新：节流、并发、账号隔离、缓存期限与非侵入更新通过');
})().catch(e=>{console.error(e);process.exitCode=1;});
