'use strict';
const assert=require('assert');
const p=require('./renderer/js/progress-report');
const catalog={11:{name:'剑圣',tags:['Fighter','Assassin']},2000:{name:'战士B',tags:['Fighter']},22:{name:'射手A',tags:['Marksman']}};
const row=(id,champion,win,queue=2400)=>({game:{gid:id,queueId:queue,dur:600,mode:'模式'+queue},me:{championId:champion,win,k:2,d:1,a:3,dmg:6000,gold:3000}});
const rows=Array.from({length:6},(_,i)=>row(i+1,2000,true));
rows.push(...Array.from({length:5},(_,i)=>row(i+10,22,i<2)));
const data=p.analyze(rows,catalog);
assert.equal(data.categories.length,7);
assert.equal(data.best.role,'Fighter');
assert.equal(data.mostPlayed.count,6);
assert.equal(data.categories.find(c=>c.role==='Assassin').count,0);
const fighter=data.categories.find(c=>c.role==='Fighter');
assert.equal(fighter.dpm,600);
assert.equal(fighter.kda,5);
assert.equal(fighter.efficiency,200);
assert.equal(fighter.tanking,null);
assert.equal(p.analyze([rows[0],rows[0]],catalog).mostPlayed.count,1);
assert.equal(p.analyze([row(100,60011,true)],catalog).mostPlayed.count,1);
assert.equal(p.analyze([row(100,999,true)],catalog).unclassified,1);
assert.equal(p.analyze(rows.concat(row(200,11,false,450)),catalog,'450').mostPlayed.count,1);
assert.equal(p.analyze([row(1,11,true)],catalog).best,null);
assert.equal(p.analyze([],catalog).mostPlayed,null);
assert(!('createGoal' in p));
assert.equal(p.classify(11,catalog[11]).role,'Attack');
assert.equal(p.classify(68,{tags:['Fighter','Mage']}).role,'SpellDps');
assert.equal(p.classify(54,{tags:['Tank','Mage']}).role,'Tank');
const items={1:{gold:{total:3000},stats:{FlatMagicDamageMod:80}},2:{gold:{total:2900},stats:{FlatMagicDamageMod:60}},3:{gold:{total:1000},stats:{FlatMagicDamageMod:40}}};
assert.equal(p.classify(54,{}, {items:[1,2]},items).role,'Burst');
assert.equal(p.classify(54,{}, {items:[1,1]},items).role,'Tank');
assert.equal(p.classify(54,{}, {items:[1,3]},items).role,'Tank');
assert.equal(p.classify(11,catalog[11], {items:[1,2]},items).role,'Attack');
assert.equal(p.classify(54,{}, {items:[1,2]},{}).role,'Tank');
assert.equal(p.classify(999,{}).role,null);
const multi=[row(300,54,true),row(301,54,false)];
multi[1].me.items=[1,2];
const mixed=p.analyze(multi,{},'',items);
assert.equal(mixed.categories.find(c=>c.role==='Burst').count,1);
assert.equal(mixed.categories.find(c=>c.role==='Tank').count,1);
assert.equal(mixed.categories.reduce((sum,c)=>sum+c.count,0),2);
assert.equal(p.analyze([row(302,60068,true)],{}).mostPlayed.role,'SpellDps');
console.log('类别画像：模式隔离、双标签去重、样本门槛、指标与缺失数据测试通过');
